const demo = [
 {title:'엔비디아의 해자는 GPU가 아니라 시스템입니다',type:'오리지널',date:'2026-08-18',views:286000,impressions:2850000,ctr:7.4,retention:58.2,subs:1820,likes:6900,comments:540},
 {title:'삼성 vs SK하이닉스, 넥스트 HBM의 승자는?',type:'칼럼',date:'2026-08-12',views:192000,impressions:2440000,ctr:6.1,retention:52.4,subs:970,likes:4100,comments:386},
 {title:'AI 데이터센터는 왜 전기를 바꾸는가',type:'오리지널',date:'2026-08-05',views:148000,impressions:2310000,ctr:4.2,retention:61.8,subs:1210,likes:4600,comments:312},
 {title:'애플은 왜 맥과 아이패드 가격을 올렸나',type:'칼럼',date:'2026-07-29',views:121000,impressions:2200000,ctr:3.8,retention:48.7,subs:510,likes:2500,comments:211},
 {title:'중국판 SpaceX, 정말 따라잡았을까?',type:'칼럼',date:'2026-07-21',views:173000,impressions:2090000,ctr:6.8,retention:43.5,subs:640,likes:3300,comments:268},
 {title:'OpenAI가 다시 판을 바꾸려는 이유',type:'오리지널',date:'2026-07-14',views:234000,impressions:3010000,ctr:6.4,retention:55.1,subs:1680,likes:5800,comments:481},
 {title:'800V DC, 엔비디아가 전력망에 손대는 이유',type:'칼럼',date:'2026-07-07',views:89000,impressions:1920000,ctr:3.2,retention:64.1,subs:760,likes:2900,comments:194},
 {title:'eSSD가 DRAM 쇼티지를 부추기는 이유',type:'칼럼',date:'2026-06-28',views:108000,impressions:1710000,ctr:4.7,retention:50.6,subs:530,likes:2300,comments:173},
 {title:'반도체 패키징, 1분 만에 이해하기',type:'쇼츠',date:'2026-06-21',views:384000,impressions:3100000,ctr:8.5,retention:71.2,subs:890,likes:9400,comments:304}
];
let data=[...demo];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('ko-KR',{notation:n>=10000?'compact':'standard',maximumFractionDigits:1}).format(n);
const median=a=>{const s=[...a].sort((x,y)=>x-y);return s.length?s[Math.floor(s.length/2)]:0};
function score(d){const v=Math.min(100,d.views/median(data.map(x=>x.views))*50),c=Math.min(100,d.ctr/6*65),r=Math.min(100,d.retention/55*70),s=Math.min(100,(d.subs/Math.max(d.views,1)*100)/.6*70);return Math.round(v*.25+c*.25+r*.3+s*.2)}
function filtered(){const days=$('#periodSelect').value;if(days==='all')return data;const max=new Date(Math.max(...data.map(d=>new Date(d.date))));return data.filter(d=>(max-new Date(d.date))/864e5<=+days)}
function render(){const d=filtered();const views=d.reduce((a,x)=>a+x.views,0), imp=d.reduce((a,x)=>a+x.impressions,0), subs=d.reduce((a,x)=>a+x.subs,0), likes=d.reduce((a,x)=>a+x.likes,0);const ctr=imp?d.reduce((a,x)=>a+x.impressions*x.ctr,0)/imp:0, ret=d.length?d.reduce((a,x)=>a+x.retention,0)/d.length:0;const channel=Math.round(d.reduce((a,x)=>a+score(x),0)/Math.max(d.length,1));
 $('#scoreValue').textContent=channel;$('#scoreRing').style.background=`conic-gradient(var(--gold) ${channel}%,#353530 0)`;
 const kpis=[['총 조회수',fmt(views),'12.8%','82'],['노출 클릭률',ctr.toFixed(1)+'%','0.6%p','64'],['평균 시청률',ret.toFixed(1)+'%','4.1%p','76'],['구독자 순증',`+${fmt(subs)}`,'18.3%','88']];
 $('#kpiGrid').innerHTML=kpis.map((x,i)=>`<div class="kpi"><div class="top"><span>${x[0]}</span><span>0${i+1}</span></div><strong>${x[1]}</strong><span class="delta">↑ ${x[2]}</span><div class="bar"><i style="width:${x[3]}%"></i></div></div>`).join('');
 renderScatter(d);renderInsights(d,ctr,ret);renderTable(d);renderCards();renderStrategy(d,ctr,ret);
}
function renderScatter(d){const maxV=Math.max(...d.map(x=>x.views),1);$('#scatter').querySelectorAll('.bubble').forEach(x=>x.remove());d.forEach((x,i)=>{const b=document.createElement('div');b.className='bubble '+(score(x)>=80?'top':'');b.style.left=`${Math.min(94,Math.max(5,x.ctr/10*100))}%`;b.style.bottom=`${Math.min(93,Math.max(5,(x.retention-30)/45*100))}%`;b.style.setProperty('--s',`${22+Math.sqrt(x.views/maxV)*28}px`);b.dataset.label=x.title.split(',')[0].slice(0,12);b.title=`${x.title}\nCTR ${x.ctr}% · 시청률 ${x.retention}%`;$('#scatter').appendChild(b)})}
function renderInsights(d,ctr,ret){const hidden=[...d].filter(x=>x.retention>ret&&x.ctr<ctr).sort((a,b)=>b.retention-a.retention)[0];const engine=[...d].sort((a,b)=>score(b)-score(a))[0];const sub=[...d].sort((a,b)=>b.subs/b.views-a.subs/a.views)[0];const items=[hidden&&[`숨은 보석의 썸네일을 교체하세요`,`${hidden.title}은 시청률 ${hidden.retention}%지만 CTR은 ${hidden.ctr}%입니다. 내용보다 패키징이 병목입니다.`],engine&&[`‘${engine.type}’ 포맷을 시리즈화하세요`,`${engine.title}이 종합 경쟁력 ${score(engine)}점으로 가장 강한 신호를 보냅니다.`],sub&&[`구독 전환 공식을 재사용하세요`,`${sub.title}은 조회 1천 회당 구독자 ${(sub.subs/sub.views*1000).toFixed(1)}명으로 가장 효율적입니다.`]].filter(Boolean);$('#insightList').innerHTML=items.map((x,i)=>`<div class="insight"><span class="num">0${i+1}</span><div><b>${x[0]}</b><p>${x[1]}</p></div></div>`).join('')}
function renderTable(d){$('#leaderboard').innerHTML=[...d].sort((a,b)=>score(b)-score(a)).slice(0,6).map((x,i)=>`<tr><td class="rank">0${i+1}</td><td class="title-cell"><b>${x.title}</b><br><small class="muted">${x.type} · ${x.date}</small></td><td class="score">${score(x)}<span class="scorebar"><i style="width:${score(x)}%"></i></span></td><td>${fmt(x.views)}</td><td>${x.ctr}%</td><td>${x.retention}%</td><td>${(x.subs/x.views*1000).toFixed(1)} /천회</td><td><span class="tag ${score(x)<70?'warn':''}">${score(x)>=80?'확장':score(x)>=70?'유지':'개선'}</span></td></tr>`).join('')}
function diagnosis(x){if(x.retention>=55&&x.ctr<5)return '내용 경쟁력은 충분합니다. 제목·썸네일 A/B 테스트가 최우선입니다.';if(x.ctr>=6&&x.retention<50)return '클릭 약속은 강하지만 초반 이탈이 큽니다. 30초 내 핵심 결론을 먼저 제시하세요.';if(score(x)>=80)return '발견과 만족이 모두 강합니다. 후속편·플레이리스트로 시청 세션을 늘리세요.';return '주제 각도와 초반 훅을 함께 재설계할 필요가 있습니다.'}
function renderCards(){const q=$('#searchInput').value.toLowerCase(),t=$('#typeFilter').value;const d=filtered().filter(x=>x.title.toLowerCase().includes(q)&&(t==='all'||x.type===t));$('#contentGrid').innerHTML=d.length?[...d].sort((a,b)=>score(b)-score(a)).map(x=>`<article class="content-card"><div class="thumb"><small>${x.type.toUpperCase()} · ${score(x)} SCORE</small><b>${x.title}</b></div><div class="card-body"><p class="card-title">${x.date} 공개</p><div class="metrics"><div><span>조회수</span><b>${fmt(x.views)}</b></div><div><span>CTR</span><b>${x.ctr}%</b></div><div><span>시청률</span><b>${x.retention}%</b></div></div><p class="diagnosis">${diagnosis(x)}</p></div></article>`).join(''):'<div class="empty">조건에 맞는 콘텐츠가 없습니다.</div>'}
function renderStrategy(d,ctr,ret){const hidden=d.filter(x=>x.retention>ret&&x.ctr<ctr).length, weak=d.filter(x=>x.ctr>=ctr&&x.retention<ret).length;const cards=[['01 · 이번 주','썸네일 재패키징',`시청 만족이 검증됐지만 덜 클릭된 ${hidden}개 영상부터 제목과 썸네일을 교체합니다.`,`CTR +1%p 목표`,`48시간 단위 비교`,`내용은 변경하지 않음`],['02 · 다음 30일','승자 포맷 시리즈화','상위 콘텐츠의 구조를 주제가 아닌 포맷으로 복제합니다.',`오리지널/칼럼 주 1회`,`제목 문법 통일`,`후속편 엔드스크린 연결`],['03 · 다음 90일','초반 이탈 구간 개선',`클릭은 되지만 유지가 약한 ${weak}개 콘텐츠의 오프닝을 재설계합니다.`,`결론을 30초 안에`,`인트로 15초 이내`,`1분 내 시청 보상 제시`]];$('#strategyGrid').innerHTML=cards.map(x=>`<article class="strategy-card"><span class="step">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><ul><li>${x[3]}</li><li>${x[4]}</li><li>${x[5]}</li></ul></article>`).join('')}
function switchView(id){$$('.view,.nav').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$(`.nav[data-view="${id}"]`).classList.add('active');$('#pageTitle').textContent={overview:'채널 개요',contents:'콘텐츠 분석',strategy:'성장 전략'}[id];window.scrollTo(0,0)}
$$('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));$('#periodSelect').onchange=render;$('#searchInput').oninput=renderCards;$('#typeFilter').onchange=renderCards;
const dialog=$('#importDialog');$('#openImport').onclick=$('#headerImport').onclick=()=>dialog.showModal();$('#loadDemo').onclick=()=>{data=[...demo];dialog.close();render()};
async function apiStatus(){try{const s=await fetch('/api/auth/status').then(r=>r.json());const b=$('#googleConnect');if(!s.configured){b.disabled=true;$('#apiStatus').textContent='Google OAuth 환경변수 설정이 필요합니다';return}b.disabled=false;$('#apiStatus').textContent=s.connected?'연결됨 · 최신 데이터 다시 가져오기':'읽기 전용 권한으로 안전하게 연결';b.onclick=s.connected?loadApiData:()=>location.href='/api/auth/start'}catch{$('#googleConnect').disabled=true;$('#apiStatus').textContent='python server.py로 실행하면 API 연결을 사용할 수 있습니다'}}
async function loadApiData(){const b=$('#googleConnect');b.disabled=true;$('#apiStatus').textContent='채널 데이터를 분석하고 있습니다…';try{const r=await fetch('/api/youtube/data'),j=await r.json();if(!r.ok)throw new Error(j.error||'데이터를 가져오지 못했습니다.');data=j.items.map(x=>({...x,type:x.type||'콘텐츠'}));dialog.close();render();document.querySelector('.status').innerHTML='<i></i> LIVE API DATA'}catch(e){$('#importError').textContent=e.message}finally{b.disabled=false}}
const aliases={title:['콘텐츠','동영상 제목','video title','content'],views:['조회수','views'],impressions:['노출수','impressions'],ctr:['노출 클릭률 (%)','노출 클릭률','impressions click-through rate (%)','ctr'],retention:['평균 조회율 (%)','평균 시청률','average percentage viewed (%)','retention'],subs:['구독자','구독자 증가','subscribers'],likes:['좋아요','likes'],comments:['댓글','comments'],date:['동영상 게시 날짜','게시 날짜','video publish time','date'],type:['콘텐츠 유형','type']};
function csvRows(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows}
function num(v){return +(String(v||0).replace(/[,%\s]/g,'').replace(/,/g,''))||0}
async function importFiles(files){try{let combined=[];for(const f of files){const rows=csvRows(await f.text());if(rows.length<2)continue;const heads=rows[0].map(x=>x.trim().toLowerCase());const idx={};for(const [k,list] of Object.entries(aliases)){idx[k]=heads.findIndex(h=>list.some(a=>h===a.toLowerCase()))}if(idx.title<0||idx.views<0)continue;combined.push(...rows.slice(1).map(r=>({title:r[idx.title]||'제목 없음',views:num(r[idx.views]),impressions:num(r[idx.impressions]),ctr:num(r[idx.ctr]),retention:num(r[idx.retention]),subs:num(r[idx.subs]),likes:num(r[idx.likes]),comments:num(r[idx.comments]),date:r[idx.date]||new Date().toISOString().slice(0,10),type:r[idx.type]||'콘텐츠'})).filter(x=>x.views>0))}if(!combined.length)throw new Error('콘텐츠와 조회수 열을 찾지 못했습니다. Studio의 콘텐츠 보고서 CSV인지 확인해주세요.');data=combined;dialog.close();render()}catch(e){$('#importError').textContent=e.message}}
$('#csvInput').onchange=e=>importFiles(e.target.files);const dz=$('#dropzone');dz.ondragover=e=>e.preventDefault();dz.ondrop=e=>{e.preventDefault();importFiles(e.dataTransfer.files)};render();
apiStatus();if(new URLSearchParams(location.search).get('connected')==='1'){history.replaceState({},'',location.pathname);loadApiData()}
