const demo = [
 {title:'엔비디아의 해자는 GPU가 아니라 시스템입니다',type:'오리지널',date:'2026-08-18',views:286000,impressions:2850000,ctr:7.4,retention:58.2,subs:1820,likes:6900,comments:540},
 {title:'삼성 vs SK하이닉스, 넥스트 HBM의 승자는?',type:'칼럼',date:'2026-08-12',views:192000,impressions:2440000,ctr:6.1,retention:52.4,subs:970,likes:4100,comments:386},
 {title:'AI 데이터센터는 왜 전기를 바꾸는가',type:'오리지널',date:'2026-08-05',views:148000,impressions:2310000,ctr:4.2,retention:61.8,subs:1210,likes:4600,comments:312},
 {title:'애플은 왜 맥과 아이패드 가격을 올렸나',type:'칼럼',date:'2026-07-29',views:121000,impressions:2200000,ctr:3.8,retention:48.7,subs:510,likes:2500,comments:211},
 {title:'중국판 SpaceX, 정말 따라잡았을까?',type:'칼럼',date:'2026-07-21',views:173000,impressions:2090000,ctr:6.8,retention:43.5,subs:640,likes:3300,comments:268},
 {title:'OpenAI가 다시 판을 바꾸려는 이유',type:'오리지널',date:'2026-07-14',views:234000,impressions:3010000,ctr:6.4,retention:55.1,subs:1680,likes:5800,comments:481},
 {title:'800V DC, 엔비디아가 전력망에 손대는 이유',type:'칼럼',date:'2026-07-07',views:89000,impressions:1920000,ctr:3.2,retention:64.1,subs:760,likes:2900,comments:194},
 {title:'eSSD가 DRAM 쇼티지를 부추기는 이유',type:'칼럼',date:'2026-06-28',views:108000,impressions:1710000,ctr:4.7,retention:50.6,subs:530,likes:2300,comments:173},
 {title:'반도체 패키징, 1분 만에 이해하기',type:'쇼츠',date:'2026-06-21',views:384000,impressions:3100000,ctr:8.5,retention:71.2,subs:890,likes:9400,comments:304}
];
let data=[...demo];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('ko-KR',{notation:n>=10000?'compact':'standard',maximumFractionDigits:1}).format(n);
const median=a=>{const s=[...a].sort((x,y)=>x-y);return s.length?s[Math.floor(s.length/2)]:0};
function score(d){const v=Math.min(100,d.views/Math.max(median(data.map(x=>x.views)),1)*50),r=Math.min(100,d.retention/55*70),s=Math.min(100,(d.subs/Math.max(d.views,1)*100)/.6*70),e=Math.min(100,((d.likes+d.comments)/Math.max(d.views,1)*100)/3*70);if(d.ctr==null)return Math.round(v*.3+r*.35+s*.2+e*.15);const c=Math.min(100,d.ctr/6*65);return Math.round(v*.25+c*.25+r*.3+s*.2)}
function filtered(){const days=$('#periodSelect').value;if(days==='all')return data;const max=new Date(Math.max(...data.map(d=>new Date(d.date))));return data.filter(d=>(max-new Date(d.date))/864e5<=+days)}
function render(){const d=filtered();const views=d.reduce((a,x)=>a+x.views,0), imp=d.reduce((a,x)=>a+(x.impressions||0),0), subs=d.reduce((a,x)=>a+x.subs,0), likes=d.reduce((a,x)=>a+x.likes,0);const ctr=imp?d.reduce((a,x)=>a+(x.impressions||0)*(x.ctr||0),0)/imp:null, ret=d.length?d.reduce((a,x)=>a+x.retention,0)/d.length:0;const channel=Math.round(d.reduce((a,x)=>a+score(x),0)/Math.max(d.length,1));
 $('#scoreValue').textContent=channel;$('#scoreRing').style.background=`conic-gradient(var(--gold) ${channel}%,#353530 0)`;
 const kpis=[['총 조회수',fmt(views),'API 집계','82'],['노출 클릭률',ctr==null?'수집 중':ctr.toFixed(1)+'%',ctr==null?'Reporting API':'노출 가중','64'],['평균 시청률',ret.toFixed(1)+'%','API 집계','76'],['구독자 순증',`+${fmt(subs)}`,'API 집계','88']];
 $('#kpiGrid').innerHTML=kpis.map((x,i)=>`<div class="kpi"><div class="top"><span>${x[0]}</span><span>0${i+1}</span></div><strong>${x[1]}</strong><span class="delta">↑ ${x[2]}</span><div class="bar"><i style="width:${x[3]}%"></i></div></div>`).join('');
 renderScatter(d);renderInsights(d,ctr,ret);renderTable(d);renderCards();renderFormatStrip(d);renderDeepAnalysis(clusterFormatData(d));renderClusters(clusterFormatData(d));renderStrategy(d,ctr,ret);
}
function renderScatter(d){const maxV=Math.max(...d.map(x=>x.views),1),hasCtr=d.some(x=>x.ctr!=null),med=Math.max(median(d.map(x=>x.views)),1);$('.x-label').innerHTML=hasCtr?'낮은 클릭률 <span>←</span> 노출 클릭률 <span>→</span> 높은 클릭률':'낮은 조회 성과 <span>←</span> 채널 중앙값 대비 <span>→</span> 높은 조회 성과';$('#scatter').querySelectorAll('.bubble').forEach(x=>x.remove());d.forEach(x=>{const b=document.createElement('div'),xpos=hasCtr?(x.ctr||0)/10*100:x.views/med*50;b.className='bubble '+(score(x)>=80?'top':'');b.style.left=`${Math.min(94,Math.max(5,xpos))}%`;b.style.bottom=`${Math.min(93,Math.max(5,(x.retention-30)/45*100))}%`;b.style.setProperty('--s',`${22+Math.sqrt(x.views/maxV)*28}px`);b.dataset.label=x.title.split(',')[0].slice(0,12);b.title=`${x.title}\n${x.ctr==null?'CTR 수집 중':'CTR '+x.ctr+'%'} · 시청률 ${x.retention}%`;$('#scatter').appendChild(b)})}
function renderInsights(d,ctr,ret){const hidden=ctr==null?null:[...d].filter(x=>x.retention>ret&&x.ctr<ctr).sort((a,b)=>b.retention-a.retention)[0];const engine=[...d].sort((a,b)=>score(b)-score(a))[0];const sub=[...d].sort((a,b)=>b.subs/b.views-a.subs/a.views)[0];const items=[hidden&&[`숨은 보석의 썸네일을 교체하세요`,`${hidden.title}은 시청률 ${hidden.retention}%지만 CTR은 ${hidden.ctr}%입니다.`],engine&&[`상위 포맷을 시리즈화하세요`,`${engine.title}이 현재 사용 가능한 지표 기준 경쟁력 ${score(engine)}점입니다.`],sub&&[`구독 전환 공식을 재사용하세요`,`${sub.title}은 조회 1천 회당 구독자 ${(sub.subs/sub.views*1000).toFixed(1)}명으로 가장 효율적입니다.`],ctr==null&&['CTR 수집을 시작했습니다','Reporting API의 reach 보고서가 생성되면 노출과 CTR을 자동 반영합니다. 현재 점수에는 CTR을 넣지 않았습니다.']].filter(Boolean);$('#insightList').innerHTML=items.slice(0,3).map((x,i)=>`<div class="insight"><span class="num">0${i+1}</span><div><b>${x[0]}</b><p>${x[1]}</p></div></div>`).join('')}
function renderTable(d){$('#leaderboard').innerHTML=[...d].sort((a,b)=>score(b)-score(a)).slice(0,6).map((x,i)=>`<tr><td class="rank">0${i+1}</td><td class="title-cell"><b>${x.title}</b><br><small class="muted">${x.type} · ${x.date}</small></td><td class="score">${score(x)}<span class="scorebar"><i style="width:${score(x)}%"></i></span></td><td>${fmt(x.views)}</td><td>${x.ctr==null?'수집 중':x.ctr+'%'}</td><td>${x.retention}%</td><td>${(x.subs/x.views*1000).toFixed(1)} /천회</td><td><span class="tag ${score(x)<70?'warn':''}">${score(x)>=80?'확장':score(x)>=70?'유지':'개선'}</span></td></tr>`).join('')}
function diagnosis(x){if(x.ctr!=null&&x.retention>=55&&x.ctr<5)return '내용 경쟁력은 충분합니다. 제목·썸네일 A/B 테스트가 최우선입니다.';if(x.ctr!=null&&x.ctr>=6&&x.retention<50)return '클릭 약속은 강하지만 초반 이탈이 큽니다. 30초 내 핵심 결론을 먼저 제시하세요.';if(score(x)>=80)return '시청 만족과 전환이 강합니다. 후속편·플레이리스트로 시청 세션을 늘리세요.';return '평균 시청률과 구독 전환을 기준으로 포맷을 재검토하세요.'}
function renderCards(){const q=$('#searchInput').value.toLowerCase(),t=$('#typeFilter').value;const d=filtered().filter(x=>x.title.toLowerCase().includes(q)&&(t==='all'||x.type===t));$('#contentGrid').innerHTML=d.length?[...d].sort((a,b)=>score(b)-score(a)).map(x=>`<article class="content-card"><div class="thumb"><small>${x.type.toUpperCase()} · ${score(x)} SCORE</small><b>${x.title}</b></div><div class="card-body"><p class="card-title">${x.date} 공개</p><div class="metrics"><div><span>조회수</span><b>${fmt(x.views)}</b></div><div><span>CTR</span><b>${x.ctr==null?'수집 중':x.ctr+'%'}</b></div><div><span>시청률</span><b>${x.retention}%</b></div></div><p class="diagnosis">${diagnosis(x)}</p></div></article>`).join(''):'<div class="empty">조건에 맞는 콘텐츠가 없습니다.</div>'}
const topicRules=[['AI·컴퓨팅',/AI|인공지능|엔비디아|NVIDIA|GPU|OpenAI|앤트로픽|클라우드|데이터센터/i],['반도체·메모리',/반도체|HBM|DRAM|낸드|메모리|패키징|삼성전자|하이닉스|TSMC|파운드리|칩/i],['우주·모빌리티',/SpaceX|우주|로켓|스타십|테슬라|자동차|배터리|모빌리티|비행기/i],['빅테크 전략',/애플|구글|메타|아마존|마이크로소프트|화웨이|퀄컴|기업|빅테크/i],['산업·에너지',/전력|전기|에너지|원전|산업|공급망|제조|로봇/i]];
function clusterName(x){for(const [name,re] of topicRules)if(re.test(x.title))return name;return '기술 인사이트'}
function clusterAction(c,channelRet,channelSub){const ret=c.ret,sub=c.sub;if(ret>=channelRet&&sub>=channelSub)return '시청 만족과 구독 전환이 함께 검증됐습니다. 같은 질문 구조로 3편짜리 후속 시리즈를 우선 제작하세요.';if(ret>=channelRet)return '끝까지 보는 힘은 강하지만 구독 전환이 약합니다. 결말에 다음 편의 질문과 구독 이유를 명확히 연결하세요.';if(sub>=channelSub)return '새 시청자를 팬으로 바꾸는 힘은 강합니다. 오프닝 설명을 압축해 평균 시청률을 끌어올리세요.';return '채널 평균보다 효율이 낮습니다. 단독 영상보다 상위 클러스터 안의 비교·후속 주제로 흡수하세요.'}
function renderClusters(d){if(!$('#clusterList'))return;const channelRet=d.reduce((a,x)=>a+x.retention,0)/Math.max(d.length,1),channelSub=d.reduce((a,x)=>a+x.subs,0)/Math.max(d.reduce((a,x)=>a+x.views,0),1)*1000,groups={};d.forEach(x=>(groups[clusterName(x)]??=[]).push(x));const cs=Object.entries(groups).map(([name,items])=>{const views=items.reduce((a,x)=>a+x.views,0),watch=items.reduce((a,x)=>a+(x.watchMinutes||x.views*(x.avgDuration||0)/60),0);return{name,items,views,med:median(items.map(x=>x.views)),ret:items.reduce((a,x)=>a+x.retention*x.views,0)/Math.max(views,1),sub:items.reduce((a,x)=>a+x.subs,0)/Math.max(views,1)*1000,eng:items.reduce((a,x)=>a+x.likes+x.comments,0)/Math.max(views,1)*100,watch}}).sort((a,b)=>(b.med*b.ret)-(a.med*a.ret));const winner=cs[0]||{name:'-',med:0,ret:0};$('#clusterSummary').innerHTML=`<div class="cluster-kicker"><span>REPEATABLE WINNER</span><h3>${winner.name}<br>클러스터가 가장 강합니다.</h3><p>단일 최고 조회수가 아니라 묶음의 조회 중앙값과 시청 만족을 함께 평가했습니다.</p></div><div class="cluster-stat"><span>최고 조회 중앙값</span><strong>${fmt(winner.med)}</strong><small class="muted">${winner.items?.length||0}개 콘텐츠 기준</small></div><div class="cluster-stat"><span>가중 평균 시청률</span><strong>${winner.ret.toFixed(1)}%</strong><small class="muted">채널 평균 ${channelRet.toFixed(1)}%</small></div>`;$('#clusterList').innerHTML=cs.map((c,i)=>{const top=[...c.items].sort((a,b)=>score(b)-score(a)).slice(0,4);const verdict=c.ret>=channelRet&&c.sub>=channelSub?'확대':c.ret>=channelRet||c.sub>=channelSub?'개선 후 확대':'축소·재설계';return `<article class="cluster-row"><div class="cluster-label"><span class="no">CLUSTER 0${i+1}</span><h3>${c.name}</h3><p>${c.items.length}개 영상의 반복 성과를 비교합니다.</p><span class="verdict">판단 · ${verdict}</span></div><div class="cluster-body"><div class="cluster-metrics"><div><span>조회 중앙값</span><b>${fmt(c.med)}</b></div><div><span>시청률</span><b>${c.ret.toFixed(1)}%</b></div><div><span>구독 전환</span><b>${c.sub.toFixed(1)} /천회</b></div><div><span>참여율</span><b>${c.eng.toFixed(2)}%</b></div></div><div class="cluster-videos">${top.map((x,n)=>`<div class="cluster-video"><small>TOP ${n+1} · SCORE ${score(x)}</small><b>${x.title}</b></div>`).join('')}<div class="cluster-action"><b>다음 액션</b> · ${clusterAction(c,channelRet,channelSub)}</div></div></div></article>`}).join('')}
function renderStrategy(d,ctr,ret){const totalViews=d.reduce((a,x)=>a+x.views,0),subRate=d.reduce((a,x)=>a+x.subs,0)/Math.max(totalViews,1)*1000,highRet=d.filter(x=>x.retention>=ret).length,highSub=d.filter(x=>x.subs/Math.max(x.views,1)*1000>=subRate).length,groups={};d.forEach(x=>(groups[clusterName(x)]??=[]).push(x));const winner=Object.entries(groups).map(([name,x])=>[name,median(x.map(v=>v.views)),x.length]).sort((a,b)=>b[1]-a[1])[0]||['상위 주제',0,0];const cards=[['01 · 다음 기획',`${winner[0]} 후속 시리즈`,`이 묶음은 한 편의 우연한 히트가 아니라 조회 중앙값이 가장 높은 반복 신호입니다.`,`3편 연속 기획`,`같은 질문 문법 유지`,`엔드스크린 상호 연결`],['02 · 오프닝','시청 보상 앞당기기',`${d.length}개 중 ${highRet}개만 채널 평균 시청률을 넘습니다. 낮은 영상은 첫 60초의 배경 설명부터 줄이세요.`,`15초 안에 핵심 질문`,`60초 안에 첫 결론`,`사례를 설명보다 먼저`],['03 · 팬 전환','구독 이유를 시리즈로 만들기',`${highSub}개 영상이 채널 평균 구독 전환 ${subRate.toFixed(1)}명/천회를 넘습니다. 이들의 다음 편 약속을 재사용하세요.`,`고정 시리즈명 부여`,`마지막 20초 다음 질문`,`상위 영상끼리 재생목록`]];$('#strategyGrid').innerHTML=cards.map(x=>`<article class="strategy-card"><span class="step">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><ul><li>${x[3]}</li><li>${x[4]}</li><li>${x[5]}</li></ul></article>`).join('')}
function switchView(id){$$('.view,.nav').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$(`.nav[data-view="${id}"]`).classList.add('active');$('#pageTitle').textContent={overview:'채널 개요',contents:'콘텐츠 분석',clusters:'콘텐츠 클러스터',strategy:'성장 전략'}[id];window.scrollTo(0,0)}
$$('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));$('#periodSelect').onchange=render;$('#searchInput').oninput=renderCards;$('#typeFilter').onchange=renderCards;
const dialog=$('#importDialog');$('#openImport').onclick=$('#headerImport').onclick=()=>dialog.showModal();$('#loadDemo').onclick=()=>{data=[...demo];dialog.close();render()};
async function apiStatus(){try{const s=await fetch('/api/auth/status').then(r=>r.json());const b=$('#googleConnect');if(!s.configured){b.disabled=true;$('#apiStatus').textContent='Google OAuth 환경변수 설정이 필요합니다';return}b.disabled=false;$('#apiStatus').textContent=s.connected?'연결됨 · 최신 데이터 다시 가져오기':'읽기 전용 권한으로 안전하게 연결';b.onclick=s.connected?loadApiData:()=>location.href='/api/auth/start'}catch{$('#googleConnect').disabled=true;$('#apiStatus').textContent='python server.py로 실행하면 API 연결을 사용할 수 있습니다'}}
async function loadApiData(){const b=$('#googleConnect');b.disabled=true;$('#apiStatus').textContent='채널 데이터를 분석하고 있습니다…';try{const r=await fetch('/api/youtube/data'),j=await r.json();if(!r.ok)throw new Error(j.error||'데이터를 가져오지 못했습니다.');data=j.items.map(x=>({...x,type:x.type||'콘텐츠'}));dialog.close();render();document.querySelector('.status').innerHTML='<i></i> LIVE API DATA'}catch(e){$('#importError').textContent=e.message}finally{b.disabled=false}}
const aliases={title:['콘텐츠','동영상 제목','video title','content'],views:['조회수','views'],impressions:['노출수','impressions'],ctr:['노출 클릭률 (%)','노출 클릭률','impressions click-through rate (%)','ctr'],retention:['평균 조회율 (%)','평균 시청률','average percentage viewed (%)','retention'],subs:['구독자','구독자 증가','subscribers'],likes:['좋아요','likes'],comments:['댓글','comments'],date:['동영상 게시 날짜','게시 날짜','video publish time','date'],type:['콘텐츠 유형','type']};
function csvRows(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows}
function num(v){return +(String(v||0).replace(/[,%\s]/g,'').replace(/,/g,''))||0}
async function importFiles(files){try{let combined=[];for(const f of files){const rows=csvRows(await f.text());if(rows.length<2)continue;const heads=rows[0].map(x=>x.trim().toLowerCase());const idx={};for(const [k,list] of Object.entries(aliases)){idx[k]=heads.findIndex(h=>list.some(a=>h===a.toLowerCase()))}if(idx.title<0||idx.views<0)continue;combined.push(...rows.slice(1).map(r=>({title:r[idx.title]||'제목 없음',views:num(r[idx.views]),impressions:num(r[idx.impressions]),ctr:num(r[idx.ctr]),retention:num(r[idx.retention]),subs:num(r[idx.subs]),likes:num(r[idx.likes]),comments:num(r[idx.comments]),date:r[idx.date]||new Date().toISOString().slice(0,10),type:r[idx.type]||'콘텐츠'})).filter(x=>x.views>0))}if(!combined.length)throw new Error('콘텐츠와 조회수 열을 찾지 못했습니다. Studio의 콘텐츠 보고서 CSV인지 확인해주세요.');data=combined;dialog.close();render()}catch(e){$('#importError').textContent=e.message}}
$('#csvInput').onchange=e=>importFiles(e.target.files);const dz=$('#dropzone');dz.ondragover=e=>e.preventDefault();dz.ondrop=e=>{e.preventDefault();importFiles(e.dataTransfer.files)};render();
apiStatus();if(new URLSearchParams(location.search).get('connected')==='1'){history.replaceState({},'',location.pathname);loadApiData()}
async function loadMarketSignals(){const groups={};data.forEach(x=>(groups[clusterName(x)]??=[]).push(x));const topics=Object.keys(groups).slice(0,6);try{const query=topics.map(x=>'topic='+encodeURIComponent(x)).join('&'),res=await fetch('/api/market/signals?'+query),j=await res.json();if(!res.ok)throw new Error(j.error);document.querySelector('.market-panel')?.remove();const cards=(j.signals||[]).map(s=>{const ours=median((groups[s.topic]||[]).map(x=>x.views)),ratio=ours/Math.max(s.competitorMedian,1);let kind,why,next;if(ratio>=1.5){kind='채널 고유 경쟁력';why='시장 상위권 중앙값보다 안될공학 묶음 성과가 높습니다.';next='설명 방식이 승리 요인입니다. 동일한 서사 구조로 후속편을 만드세요.'}else if(ratio>=.7){kind='시장 수혜 + 채널 적합';why='동일 주제 경쟁 영상과 비슷하거나 더 높은 성과입니다.';next='관심이 유지되는 동안 비교·후속 주제를 빠르게 연결하세요.'}else{kind='경쟁 과밀';why='시장 상위 영상 대비 내부 조회 중앙값이 낮습니다.';next='정면 경쟁 대신 안될공학만 설명할 기술적 질문으로 각도를 좁히세요.'}return `<div class="market-card"><span>${kind}</span><b>${s.topic}</b><p>${why}</p><small>최근 30일 경쟁 영상 ${fmt(s.supply)}개 · 경쟁 중앙값 ${fmt(s.competitorMedian)}</small><em>${next}</em></div>`}).join('');$('#clusterSummary').insertAdjacentHTML('afterend',`<section class="market-panel"><div><p class="eyebrow">MARKET CONTEXT</p><h3>성과가 나온 이유</h3></div><div class="market-grid">${cards}</div></section>`)}catch(e){console.warn('시장 신호 분석 보류',e)}}
const loadApiDataBase=loadApiData;loadApiData=async function(){await loadApiDataBase();await loadMarketSignals()}
function clusterFormatData(d){const selected=$('#clusterFormat')?.value||'all';return selected==='all'?d:d.filter(x=>x.type===selected)}
function renderFormatStrip(d){const el=$('#formatStrip');if(!el)return;const formats=['오리지널','칼럼','쇼츠','일반 영상','라이브'],totalViews=d.reduce((a,x)=>a+x.views,0);el.innerHTML=formats.map(name=>{const items=d.filter(x=>x.type===name);if(!items.length)return '';const views=items.reduce((a,x)=>a+x.views,0),ret=items.reduce((a,x)=>a+x.retention*x.views,0)/Math.max(views,1),subs=items.reduce((a,x)=>a+x.subs,0)/Math.max(views,1)*1000,role=name==='쇼츠'?'발견·신규 유입':name==='오리지널'?'깊은 시청·브랜드':name==='칼럼'?'시의성·관점':name==='라이브'?'관계·체류':'기본 도달';return `<button class="format-card ${$('#clusterFormat').value===name?'active':''}" data-format="${name}"><span>${name}</span><strong>${items.length}편</strong><small>조회 비중 ${(views/Math.max(totalViews,1)*100).toFixed(1)}% · 시청률 ${ret.toFixed(1)}%</small><em>${role} · 구독 ${subs.toFixed(1)}/천회</em></button>`}).join('');el.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{$('#clusterFormat').value=$('#clusterFormat').value===b.dataset.format?'all':b.dataset.format;render()})}
$('#clusterFormat').onchange=render;
function correlation(a,b){if(a.length<3)return 0;const ma=a.reduce((x,y)=>x+y,0)/a.length,mb=b.reduce((x,y)=>x+y,0)/b.length,top=a.reduce((s,x,i)=>s+(x-ma)*(b[i]-mb),0),bot=Math.sqrt(a.reduce((s,x)=>s+(x-ma)**2,0)*b.reduce((s,x)=>s+(x-mb)**2,0));return bot?top/bot:0}
function renderDeepAnalysis(d){
  const el=$('#deepDive');
  if(!el||!d.length){if(el)el.innerHTML='';return}
  const sorted=[...d].sort((a,b)=>b.views-a.views);
  const cut=Math.max(1,Math.ceil(d.length*.1)),top=sorted.slice(0,cut),rest=sorted.slice(cut);
  const m=x=>median(x),rate=x=>x.subs/Math.max(x.views,1)*1000,eng=x=>(x.likes+x.comments)/Math.max(x.views,1)*100;
  const topRet=m(top.map(x=>x.retention)),baseRet=m(rest.map(x=>x.retention));
  const topSub=m(top.map(rate)),baseSub=m(rest.map(rate));
  const logViews=d.map(x=>Math.log1p(x.views)),retCorr=correlation(logViews,d.map(x=>x.retention)),engCorr=correlation(logViews,d.map(eng));
  const format=$('#clusterFormat').value==='all'?'전체 포맷':$('#clusterFormat').value;
  let verdict;
  if(format==='쇼츠') verdict='쇼츠는 높은 완주보다 롱폼으로 넘기는 연결성과 주제 테스트 성공률을 핵심 목표로 삼아야 합니다.';
  else if(topSub>baseSub*1.4) verdict='상위 콘텐츠의 핵심 강점은 단순 조회가 아니라 신규 시청자를 구독자로 바꾸는 전문성과 주제 선택입니다.';
  else verdict='상위 콘텐츠의 공통점을 제목보다 시청 만족과 참여 반응에서 찾아 후속 포맷으로 고정해야 합니다.';
  const cards=[
    ['TOP 10% DNA','상위권 구독 전환',topSub.toFixed(1)+'명','나머지 중앙값 '+baseSub.toFixed(1)+'명/천회',topSub>baseSub?'전문성·후속 기대가 히트의 핵심':'구독 전환보다 도달 기여가 큼','positive'],
    ['WHAT DRIVES VIEWS','조회와 참여의 관계',engCorr.toFixed(2),'시청률 상관 '+retCorr.toFixed(2),engCorr>retCorr?'댓글·좋아요를 부르는 논점이 조회 확장과 더 가깝습니다.':'시청 지속이 조회 확장과 더 가깝습니다.',''],
    ['RETENTION REALITY','상위권 시청률',topRet.toFixed(1)+'%','나머지 중앙값 '+baseRet.toFixed(1)+'%',topRet<baseRet?'대형 조회 영상은 넓은 유입 때문에 시청률이 낮아져도 실패가 아닙니다.':'상위권은 시청 만족도 함께 강합니다.',''],
    ['PORTFOLIO ROLE',format==='쇼츠'?'쇼츠의 역할':'롱폼의 역할',format==='쇼츠'?'주제 검증':'팬 전환',format==='쇼츠'?'구독보다 롱폼 이동을 측정':'조회 1천 회당 구독을 측정',verdict,format==='쇼츠'?'critical':'positive'],
    ['NEXT TEST','다음 4편 실험','2 × 2','상위 주제 2개 × 서사 2개','같은 주제에서 오프닝 구조만 바꿔 주제 효과와 제작 효과를 분리하세요.',''],
    ['STOP RULE','중단 기준',m(d.map(x=>x.views)).toLocaleString()+'회','현재 포맷 조회 중앙값','2편 연속 중앙값 미달이면서 구독 전환도 하위 50%면 해당 조합을 중단하세요.','critical']
  ];
  const cardHtml=cards.map(x=>'<article class="deep-card '+x[5]+'"><span class="signal">'+x[0]+'</span><h4>'+x[1]+'</h4><strong>'+x[2]+'</strong><div class="evidence">'+x[3]+'</div><p>'+x[4]+'</p></article>').join('');
  el.innerHTML='<div class="deep-head"><div><p class="eyebrow">DEEP DIAGNOSIS · '+format+'</p><h3>조회수가 아니라<br>반복 가능한 원인을 봅니다.</h3><p>'+d.length+'편의 상위 10%와 나머지를 분리해 성과 차이를 계산했습니다.</p></div><div class="deep-verdict"><span>EXECUTIVE VERDICT</span><b>'+verdict+'</b></div></div><div class="deep-grid">'+cardHtml+'</div>';
}
